### ISSUE TITLE
BigARTM Coredump on Linux in google::LogMessage::~LogMessage

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#143]
Runninng python examples on Linux sometimes causes core dump.
I managed to get callstacks with the following tricks:

>sudo apt-get install gdb python2.7-dbg
>ulimit -c unlimited
>python example04_online_algorithm.py          <- produces 'core' file
>gdb python core   
>thread apply all where          <-  gets callstack for all threads

I think the problem is in google logging that does not handle situation when multiple threads write the first message simultaneously.

```javascript
(gdb) thread apply all where

Thread 4 (Thread 0x7f37f8f49740 (LWP 6590)):
#0  0x00007f37f6322130 in master_component(int) () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#1  0x00007f37f6327d7c in ArtmReconfigureMasterComponent () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#2  0x00007f37f694dadc in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#3  0x00007f37f694d40c in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#4  0x00007f37f6b646ce in _call_function_pointer (argcount=3, resmem=0x7fff3296c6f0, restype=<optimized out>,
    atypes=<optimized out>, avalues=0x7fff3296c6c0, pProc=0x7f37f6327d40 <ArtmReconfigureMasterComponent>,
    flags=4353) at /build/buildd/python2.7-2.7.5/Modules/_ctypes/callproc.c:836
#5  _ctypes_callproc (pProc=pProc@entry=0x7f37f6327d40 <ArtmReconfigureMasterComponent>,
    argtuple=argtuple@entry=0x2315fa0, flags=4353, argtypes=argtypes@entry=0x0, restype=restype@entry=0x23458f0,
    checker=checker@entry=0x0) at /build/buildd/python2.7-2.7.5/Modules/_ctypes/callproc.c:1183
#6  0x00007f37f6b6606e in PyCFuncPtr_call (self=<optimized out>, inargs=<optimized out>, kwds=<optimized out>)
    at /build/buildd/python2.7-2.7.5/Modules/_ctypes/_ctypes.c:3929
#7  0x0000000000561669 in PyObject_Call (kw=0x0, arg=0x2315fa0, func=0x2aeb050) at ../Objects/abstract.c:2529
#8  do_call (nk=<optimized out>, na=<optimized out>, pp_stack=0x7fff3296ca40, func=0x2aeb050)
    at ../Python/ceval.c:4239
#9  call_function (oparg=<optimized out>, pp_stack=0x7fff3296ca40) at ../Python/ceval.c:4044
#10 PyEval_EvalFrameEx (f=f@entry=0x2371450, throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#11 0x000000000054b7d4 in PyEval_EvalCodeEx (co=0x1d126b0, globals=<optimized out>, locals=locals@entry=0x0,
    args=<optimized out>, argcount=argcount@entry=1, kws=<optimized out>, kwcount=kwcount@entry=0,
    defs=defs@entry=0x232d2a8, defcount=1, closure=0x0) at ../Python/ceval.c:3253
#12 0x00000000005614dd in fast_function (nk=0, na=1, n=<optimized out>, pp_stack=0x7fff3296cc60, func=0x232f410)
    at ../Python/ceval.c:4117
#13 call_function (oparg=<optimized out>, pp_stack=0x7fff3296cc60) at ../Python/ceval.c:4042
#14 PyEval_EvalFrameEx (f=f@entry=0x1cf30b0, throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#15 0x000000000054b7d4 in PyEval_EvalCodeEx (co=0x7f37f8e3b130, globals=<optimized out>, locals=<optimized out>,
    args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, defcount=0,
    closure=0x0) at ../Python/ceval.c:3253
#16 0x000000000055830c in PyEval_EvalCode (locals=0x1c5a7b0, globals=0x1c5a7b0, co=0x7f37f8e3b130)
    at ../Python/ceval.c:667
#17 run_mod.42568 (mod=mod@entry=0x1c5eb78,
    filename=filename@entry=0x7fff3296ed26 "example04_online_algorithm.py", globals=globals@entry=0x1c5a7b0,
    locals=locals@entry=0x1c5a7b0, flags=flags@entry=0x7fff3296cf50, arena=arena@entry=0x1ce6070)
    at ../Python/pythonrun.c:1365
#18 0x0000000000468567 in PyRun_FileExFlags (fp=fp@entry=0x1cf8710,
    filename=filename@entry=0x7fff3296ed26 "example04_online_algorithm.py", start=start@entry=257,
    globals=globals@entry=0x1c5a7b0, locals=locals@entry=0x1c5a7b0, closeit=closeit@entry=1,
    flags=flags@entry=0x7fff3296cf50) at ../Python/pythonrun.c:1351
#19 0x0000000000468aa0 in PyRun_SimpleFileExFlags (fp=fp@entry=0x1cf8710, filename=<optimized out>,
    filename@entry=0x7fff3296ed26 "example04_online_algorithm.py", closeit=closeit@entry=1,
    flags=flags@entry=0x7fff3296cf50) at ../Python/pythonrun.c:943
#20 0x0000000000468b9c in PyRun_AnyFileExFlags (fp=fp@entry=0x1cf8710,
    filename=filename@entry=0x7fff3296ed26 "example04_online_algorithm.py", closeit=closeit@entry=1,
    flags=flags@entry=0x7fff3296cf50) at ../Python/pythonrun.c:747
#21 0x000000000046a1e3 in Py_Main (argc=<optimized out>, argv=0x7fff3296d108) at ../Modules/main.c:640
#22 0x00007f37f8776de5 in __libc_start_main (main=0x46a2a1 <main>, argc=2, ubp_av=0x7fff3296d108,
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff3296d0f8)
    at libc-start.c:260
#23 0x00000000005735fe in _start ()

Thread 3 (Thread 0x7f37f4635700 (LWP 6594)):
#0  0x00007f37f8b2c47d in open64 () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f37f64730c1 in google::(anonymous namespace)::LogFileObject::CreateLogfile(std::string const&) ()
   from /home/ubuntu/bigartm/build/src/artm/libartm.so
#2  0x00007f37f647acf1 in google::(anonymous namespace)::LogFileObject::Write(bool, long, char const*, int) ()
   from /home/ubuntu/bigartm/build/src/artm/libartm.so
#3  0x00007f37f64783de in google::LogMessage::SendToLog() () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#4  0x00007f37f6474383 in google::LogMessage::Flush() () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#5  0x00007f37f6474489 in google::LogMessage::~LogMessage() () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#6  0x00007f37f6397cc3 in artm::core::Merger::ThreadFunction() ()
---Type <return> to continue, or q <return> to quit---
   from /home/ubuntu/bigartm/build/src/artm/libartm.so
#7  0x00007f37f601894a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.53.0
#8  0x00007f37f8b24f6e in start_thread (arg=0x7f37f4635700) at pthread_create.c:311
#9  0x00007f37f884f9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 2 (Thread 0x7f37f3e34700 (LWP 6595)):
#0  0x00007f37f5520141 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007f37f63f0b3d in std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&) ()
   from /home/ubuntu/bigartm/build/src/artm/libartm.so
#2  0x00007f37f6479cc9 in google::GetLoggingDirectories() () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#3  0x00007f37f647ac21 in google::(anonymous namespace)::LogFileObject::Write(bool, long, char const*, int) ()
   from /home/ubuntu/bigartm/build/src/artm/libartm.so
#4  0x00007f37f64783de in google::LogMessage::SendToLog() () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#5  0x00007f37f6474383 in google::LogMessage::Flush() () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#6  0x00007f37f6474489 in google::LogMessage::~LogMessage() () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#7  0x00007f37f63ab359 in artm::core::Processor::ThreadFunction() ()
   from /home/ubuntu/bigartm/build/src/artm/libartm.so
#8  0x00007f37f601894a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.53.0
#9  0x00007f37f8b24f6e in start_thread (arg=0x7f37f3e34700) at pthread_create.c:311
#10 0x00007f37f884f9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 1 (Thread 0x7f37f4e36700 (LWP 6593)):
#0  0x00007f37f5520141 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007f37f63f0b3d in std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&) ()
   from /home/ubuntu/bigartm/build/src/artm/libartm.so
#2  0x00007f37f6479cc9 in google::GetLoggingDirectories() () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#3  0x00007f37f647ac21 in google::(anonymous namespace)::LogFileObject::Write(bool, long, char const*, int) ()
   from /home/ubuntu/bigartm/build/src/artm/libartm.so
#4  0x00007f37f64783de in google::LogMessage::SendToLog() () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#5  0x00007f37f6474383 in google::LogMessage::Flush() () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#6  0x00007f37f6474489 in google::LogMessage::~LogMessage() () from /home/ubuntu/bigartm/build/src/artm/libartm.so
#7  0x00007f37f63bec90 in artm::core::LocalDataLoader::ThreadFunction() ()
   from /home/ubuntu/bigartm/build/src/artm/libartm.so
#8  0x00007f37f601894a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.53.0
#9  0x00007f37f8b24f6e in start_thread (arg=0x7f37f4e36700) at pthread_create.c:311
#10 0x00007f37f884f9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by bigartm** [comment]
Fixed by https://github.com/bigartm/bigartm/commit/9570e117f703291ed77d7b173f5c24d795d340bd (workaround)
