### ISSUE TITLE
Can't install on Amazon linux

### ISSUE THREAD

**Issue by ohld** [bigartm/bigartm#711]
I tried to install your library on  Amazon linux. 
I did all steps mentioned here: https://github.com/bigartm/bigartm/blob/master/docs/installation/linux.txt

Command `bigartm --help` works fine:

> BigARTM v0.8.2 - library for advanced topic modeling (http://bigartm.org):   
> ...

But then i run python and try in python (which is python 3.5 by default):
`import artm; print(artm.version()); print(artm.ARTM(num_topics=10).info)`
it says:
> ImportError: No module named 'artm'

When i do the same line but with python2 it says: 

> Traceback (most recent call last):                                                                                                 
  File "<stdin>", line 1, in <module>                                                                                              
  File "build/bdist.linux-x86_64/egg/artm/__init__.py", line 1, in <module>                                                        
  File "build/bdist.linux-x86_64/egg/artm/artm_model.py", line 9, in <module>                                                      
  File "/usr/lib/python2.7/dist-packages/pandas/__init__.py", line 45, in <module>                                                 
    from pandas.io.api import *                                                                                                    
  File "/usr/lib/python2.7/dist-packages/pandas/io/api.py", line 13, in <module>                                                   
    from pandas.io.pickle import read_pickle, to_pickle                                                                            
  File "/usr/lib/python2.7/dist-packages/pandas/io/pickle.py", line 1, in <module>                                                 
    from pandas.compat import cPickle as pkl, pickle_compat as pc, PY3                                                             
  File "/usr/lib/python2.7/dist-packages/pandas/compat/pickle_compat.py", line 100, in <module>                                    
    class DeprecatedSeries(np.ndarray, Series):                                                                                    
AttributeError: 'module' object has no attribute 'ndarray'

**Comment by ohld** [comment]
I did all commands mentioned in link above: https://github.com/bigartm/bigartm/blob/master/docs/installation/linux.txt
All commands completed successfully without any errors or warnings.

**Comment by JeanPaulShapo** [comment]
@ohld 
* By default BigARTM builds against `python2`, that's why there is no module *artm* for `python3.5`. You have to add option ``-DPYTHON=python3`` to `cmake` command in order [to build module for `python3.5`](https://github.com/bigartm/bigartm/blob/master/docs/installation/linux.txt#L146)
* As for the second issue, there may be some problems with python packages installed system-wide. I recommend install necessary packages manually using `pip`, as suggested [in this part of tutorial](https://github.com/bigartm/bigartm/blob/master/docs/installation/linux.txt#L115). Personally I use [`virtualenv`](https://virtualenv.pypa.io/en/stable/) to split different environments for different tasks and to avoid dependency on system-wide python packages as much as possible.

Btw, I don't have much experience with Amazon Linux. Could you name the distribution and architecture?

**Comment by ohld** [comment]
Thank you so much - the problem was in the _pandas_ package. I just reinstalled it and now _artm_ works.
