### ISSUE TITLE
Can't run VisARTM 

### ISSUE THREAD

**Issue by akrot** [bigartm/bigartm#766]
After installing BigARTM, I tried to install VisARTM and on the step:

**python manage.py makemigrations**

I have the following error:

models.models import ArtmModel, Topic, TopicInTopic

C:\BigARTM\visartm>python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Krot-AV\Anaconda2\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\Krot-AV\Anaconda2\lib\site-packages\django\core\management\__init__.py", line 341, in execute
    django.setup()
  File "C:\Users\Krot-AV\Anaconda2\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Krot-AV\Anaconda2\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Users\Krot-AV\Anaconda2\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Krot-AV\Anaconda2\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\BigARTM\visartm\visual\models.py", line 3, in <module>
    from models.models import ArtmModel, Topic, TopicInTopic
ImportError: No module named models

C:\BigARTM\visartm>
C:\BigARTM\visartm>
C:\BigARTM\visartm>python
Python 2.7.13 |Anaconda 4.3.0 (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import artm
>>>

**Comment by Angriff** [comment]
May be it is not the reason of your problem, but note that VisARTM requires python 3

> Make sure you have installed python 3.
