### ISSUE TITLE
Invalid 'length' parameter error in model.transform()

### ISSUE THREAD

**Issue by mannefedov** [bigartm/bigartm#849]
I trained a model and tried to transform the dataset with it, however after some time I got the following error:

```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "D:\nefedov\Continuum\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\nefedov\Continuum\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\nefedov\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\nefedov\bigartm\python\artm\master_component.py", line 870, in transform
    self._lib.ArtmCopyRequestedObject(numpy_ndarray)
  File "D:\nefedov\bigartm\python\artm\wrapper\api.py", line 148, in artm_api_call
    self._check_error(result)
  File "D:\nefedov\bigartm\python\artm\wrapper\api.py", line 84, in _check_error
    raise exception_class(error_message)
artm.wrapper.exceptions.InvalidOperationException: Invalid 'length' parameter (3067573200 expected, found -1227394096).
```
What can the problem be?

**Comment by MelLain** [comment]
What is the size of your dataset and the batch you try to transform? ---С уважением, Мурат Апишев.Моя страница на machinelearning.ru Regards, Murat Apishev.03.11.2017, 16:46, "manefedov" <notifications@github.com>:I trained a model and tried to transform the dataset with it, however after some time I got the following error:
Exception in thread Thread-11:
Traceback (most recent call last):
  File "D:\nefedov\Continuum\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\nefedov\Continuum\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\nefedov\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\nefedov\bigartm\python\artm\master_component.py", line 870, in transform
    self._lib.ArtmCopyRequestedObject(numpy_ndarray)
  File "D:\nefedov\bigartm\python\artm\wrapper\api.py", line 148, in artm_api_call
    self._check_error(result)
  File "D:\nefedov\bigartm\python\artm\wrapper\api.py", line 84, in _check_error
    raise exception_class(error_message)
artm.wrapper.exceptions.InvalidOperationException: Invalid 'length' parameter (3067573200 expected, found -1227394096).

What can the problem be?

**Comment by mannefedov** [comment]
When checking batchsize I noticed that the number is different from the one I specified while batching (1000 instead of 10000). I rebatched the dataset and transform seems to work fine now. However, batchsize still changes to 1000 when I initialize the batch_vectorizer from batches and not from original .vw file. Even though transform does not throw an exception I guess it's not good.
In case that matters, the dataset is 2556311 documents.

**Comment by MelLain** [comment]
Batchsize from Vectorizer means real batch size only while creating batches. Vectorizer knows nothing about the size of loaded ready batches, as it does not look into them for speed reasons, so it uses default value. ---С уважением, Мурат Апишев.Моя страница на machinelearning.ruRegards, Murat Apishev.03.11.2017, 18:31, "manefedov" <notifications@github.com>:When checking batchsize I noticed that the number is different from the one I specified while batching (1000 instead of 10000). I rebatched the dataset and transform seems to work fine now. However, batchsize still changes to 1000 when I initialize the batch_vectorizer from batches and not from original .vw file. Even though transform does not throw an exception I guess it's not good.
In case that matters, the dataset is 2556311 documents.
