### ISSUE TITLE
Invalid 'length' parameter

### ISSUE THREAD

**Issue by MasYes** [bigartm/bigartm#860]
Hi all,
I'm having a problem with hARTM. I have a big collection of documents (~7,5M items, ~6M words) and I'm trying to creat a hierarhical model with 10 topics on the first level and 70 on the second one.
Model's fitting went fine, but when I tried to save the second level matrix (**model.get_level(1).get_theta()**) I got the exception:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "main/server_functions.py", line 136, in <module>
    create_model_in_folder()
  File "main/server_functions.py", line 40, in create_model_in_folder
    topic_model.save_models_matrixes()
  File "modelling/topic_model_2lvl.py", line 395, in save_models_matrixes
    model_lvl2.get_theta().to_pickle('{}/theta_lvl2.pkl.bz2'.format(path_to_folder), compression='bz2')
  File "/usr/local/lib/python2.7/dist-packages/artm/hierarchy_utils.py", line 651, in get_theta
    _, nd_array = self.master.get_theta_matrix(topic_names=use_topic_names)
  File "/usr/local/lib/python2.7/dist-packages/artm/master_component.py", line 728, in get_theta_matrix
    self._lib.ArtmCopyRequestedObject(numpy_ndarray)
  File "/usr/local/lib/python2.7/dist-packages/artm/wrapper/api.py", line 161, in artm_api_call
    self._check_error(result)
  File "/usr/local/lib/python2.7/dist-packages/artm/wrapper/api.py", line 97, in _check_error
    raise exception_class(error_message)
artm.wrapper.exceptions.InvalidOperationException: Invalid 'length' parameter (2396834388 expected, found -1898132908)

There's no problem with the first level, phi and modalities, they were saved OK. The problem occurs only with the theta on the second level. I don't know if it's my fault or not. It seems like variable overflow, since unsigned -1898132908 equals 2396834388.

If anyone could suggest a solution that would be great.

**Comment by JeanPaulShapo** [comment]
@MasYes 
As we use [Google Protocol Buffers](https://github.com/google/protobuf) under the hood to serialize models between BigARTM core and high-level APIs, it's very likely that you've hit their main limitation of maximum message length, which equals to 2^31 - 1.

To avoid this limitation right now, you can request your theta matrix in chunks, using optional parameter `topic_names` in `ARTM_level.get_theta` function.

**Comment by ofrei** [comment]
@MasYes In general I agree with @JeanPaulShapo suggestion. If chunking by topic names is not very handy you may chunk by batches (e.g. subsets of documents) -- personally I think it would be a better option. 

Having said that, I believe the specific error that you get is an old issue which is fixed in the latest version of the BigARTM. The size of you matrix is 7.5M*70*sizeof(float)=2.1 GB. We transfer this from C++ to python part of the library via single memory buffer (@JeanPaulShapo not via protobuf message). Previously the buffer was limited by int. Some time ago things changed and we switched to int64_t.

**Comment by ofrei** [comment]
@MasYes if this issue is still a problem please send me which version of BigARTM do you use, and I will help investigate.
