### ISSUE TITLE
_wait_for_batches_processed may hang in ARTM.fit_offline()

### ISSUE THREAD

**Issue by ofrei** [bigartm/bigartm#883]
This snipped cause ARTM.fit_offline() to hang.
```
model = artm.ARTM(num_topics=10, num_processors=4, theta_columns_naming='title')
model.initialize(dictionary=artm.Dictionary(data_path=r'H:\datasets\vw.mmro.batches'))
model.fit_offline(num_collection_passes=10, batch_vectorizer=artm.BatchVectorizer(r'H:\datasets\vw.mmro.batches', data_format='batches'))
```
It happens because I fogrot ``data_path=`` in the definition, and I'm getting this funny messages in the log:
```
E0228 13:56:58.000409 34980 processor.cc:985] Unable to open file H, the batch will be skipped.
E0228 13:56:58.000409 16380 processor.cc:985] Unable to open file :, the batch will be skipped.
E0228 13:56:58.009413 16000 processor.cc:985] Unable to open file \, the batch will be skipped.
E0228 13:56:58.010401 34212 processor.cc:985] Unable to open file d, the batch will be skipped.
E0228 13:56:58.010401 34980 processor.cc:985] Unable to open file a, the batch will be skipped.
E0228 13:56:58.011409 16380 processor.cc:985] Unable to open file t, the batch will be skipped.
E0228 13:56:58.242693 16380 processor.cc:985] Unable to open file s, the batch will be skipped.
E0228 13:56:58.238699 16000 processor.cc:985] Unable to open file a, the batch will be skipped.
...
```
and `fit_offline` crashes with exception:
```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Anaconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "H:\GitHub\bigartm\bigartm\python\artm\master_component.py", line 882, in fit_offline
    self._lib.ArtmFitOfflineMasterModel(self.master_id, args)
  File "H:\GitHub\bigartm\bigartm\python\artm\wrapper\api.py", line 161, in artm_api_call
    self._check_error(result)
  File "H:\GitHub\bigartm\bigartm\python\artm\wrapper\api.py", line 97, in _check_error
    raise exception_class(error_message)
artm.wrapper.exceptions.InvalidOperationException: FitOffline: no batches to process
```
However my ipython session hangs, and I see repeated messages `_wait_for_batches_processed` from in the log:
```
I0228 14:27:14.149011 29544 c_interface.cc:562] Pass GetScoreValueArgs, score_name=^^^ItemsProcessedScore^^^ to MasterComponent::Request
I0228 14:27:14.149011 29544 c_interface.cc:231] ArtmCopyRequestedMessage is copying 31 bytes...
```

So for some reason ``while not async_result.ready():`` never exit.

**Comment by ofrei** [comment]
I'm not sure how to address this. One way would be to step back from calling fit_offline / fit_online / transform asynchronously (e.g. do so only if user requested progress bar, which is off by default).

**Comment by ofrei** [comment]
Fixed by https://github.com/bigartm/bigartm/pull/908
